# Generated by Django 4.2.2 on 2023-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mh_rating', models.IntegerField(choices=[(5, 'Best'), (4, ''), (3, 'Middle'), (2, ''), (1, 'Worst')])),
                ('env_rating', models.IntegerField(choices=[(5, 'Best'), (4, ''), (3, 'Middle'), (2, ''), (1, 'Worst')])),
                ('diet_change', models.BooleanField()),
                ('exercise', models.BooleanField()),
                ('med_change', models.BooleanField()),
                ('sleep_well', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_logged', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
