# Generated by Django 4.2.2 on 2023-06-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentallog',
            name='diet_change',
            field=models.BooleanField(verbose_name='diet change?'),
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='env_rating',
            field=models.IntegerField(choices=[(5, '5 - Best'), (4, '4'), (3, '3 -Middle'), (2, '2'), (1, '1 - Worst')], default=5, verbose_name='daily environment rating'),
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='exercise',
            field=models.BooleanField(verbose_name='exercise today?'),
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='med_change',
            field=models.BooleanField(verbose_name='medication change?'),
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='mh_rating',
            field=models.IntegerField(choices=[(5, '5 - Best'), (4, '4'), (3, '3 -Middle'), (2, '2'), (1, '1 - Worst')], default=5, verbose_name='mental health rating'),
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='personal notes'),
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='sleep_well',
            field=models.BooleanField(verbose_name='sleep well?'),
        ),
    ]
