# Generated by Django 4.2.2 on 2023-06-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhtracker', '0003_mentallog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentallog',
            name='med_change',
            field=models.BooleanField(verbose_name='took medication?'),
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='sleep_well',
            field=models.IntegerField(choices=[(5, '5 - Best'), (4, '4'), (3, '3 -Middle'), (2, '2'), (1, '1 - Worst')], default=5, verbose_name='sleep quality'),
        ),
    ]
