# Generated by Django 4.2.2 on 2023-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhtracker', '0004_alter_mentallog_med_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentallog',
            name='med_change',
        ),
        migrations.RemoveField(
            model_name='mentallog',
            name='sleep_well',
        ),
        migrations.AddField(
            model_name='mentallog',
            name='sleep_quality',
            field=models.IntegerField(choices=[(5, '5 - Best'), (4, '4'), (3, '3 - Middle'), (2, '2'), (1, '1 - Worst')], default=5, verbose_name='sleep quality'),
        ),
        migrations.AddField(
            model_name='mentallog',
            name='took_med',
            field=models.BooleanField(default=False, verbose_name='took medicine?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='env_rating',
            field=models.IntegerField(choices=[(5, '5 - Best'), (4, '4'), (3, '3 - Middle'), (2, '2'), (1, '1 - Worst')], default=5, verbose_name='daily environment rating'),
        ),
        migrations.AlterField(
            model_name='mentallog',
            name='mh_rating',
            field=models.IntegerField(choices=[(5, '5 - Best'), (4, '4'), (3, '3 - Middle'), (2, '2'), (1, '1 - Worst')], default=5, verbose_name='mental health rating'),
        ),
    ]
